### ISSUE TITLE
Media saving options not displayed until after phone restart

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1762]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Media saving options not displayed in the long-press on message bubble option until after phone restarted

### Steps to reproduce
- Receive picture in group chat
- Press & hold on message bubble to see option to save image

**Actual result:** Saw options for copy and delete, not save.  Restarted phone then saw options for copy, delete, and save. 
**Expected result:** See this option without a phone restart

### Screenshots

N/A

### Device info

**Device**: iPhone 7
**iOS version**: 10.2.1
**Signal version:** 2.6.15

### Link to debug log

 https://gist.github.com/anonymous/c30b5448c8edd49682046f9e6d6d4425

**Comment by michaelkirk** [comment]
@charlesmchen is this the same thing fixed by 6a3b462541d290b7fb80d31f61ff26c06f900fdb (not yet released).

**Comment by arekm** [comment]
There is still a problem with Saving.

For example when image is received from person X and I long click on it immediately there is only Copy/Delete (I have it in non english, so my translation can be inaccurate to what signal uses in native english). No Save, no other options.

I need to go "back" to conversations list, then go again to person X messages list and then long press - Save (and few other options) is now there.

**Comment by michaelkirk** [comment]
@riyapenn - IIRC we made some related changes to how the menu items get juggled around which may fix this. Can you still reproduce?

**Comment by denver-s** [comment]
I do not experience this bug (2.38.1.2).

**Comment by michaelkirk-signal** [comment]
Please re-open with a fresh debug log and steps if you can still reproduce this.
