### ISSUE TITLE
Select and send multiple photos

### ISSUE THREAD

**Issue by jocap** [signalapp/Signal-iOS#2890]
- [x] I have searched open and closed issues for duplicates

(Note that #2409 is a duplicate, but it was closed by the reporter, so it hasn't received any attention, even after subsequent comments.)

----------------------------------------

### Bug description
There currently isn't a way to select and send multiple photos from the photo gallery at once.

This is a big issue for people who like sharing a lot of photos, preventing them from using Signal and making some of them resort to alternatives like Facebook Messenger.

### Steps to reproduce
- Open conversation
- Click on paper clip and select photo gallery
- Click on a photo

**Actual result:** The single photo is attached to the message.
**Expected result:** The photo should be *selected* but not immediately attached, allowing for more photos to be selected and finally attached by pressing an "OK" button (or something similar).

### Device info

**Device**: iPhone 7
**iOS version**: 11.0.3
**Signal version:** 2.19.3.3 and earlier

**Comment by NinebitX** [comment]
Is this a dupe of https://github.com/WhisperSystems/Signal-iOS/issues/858?

**Comment by jocap** [comment]
@NinebitX Hm, yes, it might be. I'm a little confused by that issue, though, as it seems to focus on a few different things, some of which seem to have been fixed. For example, I believe that you indeed *can* preview images in the current version of Signal, can't you? In any case, that bounty looks at least a bit promising. I suppose I will close this issue tomorrow and refer to #858.

**Comment by Tlamatinime** [comment]
With the new release, this issue can be closed. Correct?

**Comment by NinebitX** [comment]
Right, this issue is now fixed in version 2.34.0.

**Comment by tzs1** [comment]
@michaelkirk-signal you can close this issue.

**Comment by IntrepidWhelk** [comment]
This issue is still unresolved as of the most recent version of Signal on my iPhone (2.43.3). 

To recreate go into a conversation / group, tap on a photo, tap on ‘All Media’ top right, tap Select, select a bunch of photos. The only option at the bottom is to delete, there is no option to select and copy.

**Comment by michaelkirk-signal** [comment]
@IntrepidWhelk - this issue was about sending multiple items from your system photo library, which was added some time ago.

To use it:
- tap the "+" to open the attachments menu
- choose "media library"
- select each item you'd like to send

It sounds like you are requesting the ability to copy multiple items from your per-conversation media gallery to the clipboard. That's an interesting idea. If you'd like you can discuss it on the community forums https://community.signalusers.org where we discuss feature requests.
