### ISSUE TITLE
Swiping left for message details is difficult for short messages

### ISSUE THREAD

**Issue by mmiller42** [signalapp/Signal-iOS#2963]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
To see details of a message such as sent and received time, you have to swipe right to left on the message. For short messages this is difficult to impossible to do.

You can long press and select Info, but this does not work if the short message is a link. For example, if you send a message that contains the text “12:00”, it will create a link to open iOS calendar app to create an event. Because the message cannot be long pressed for info and is too short to swipe right, it is difficult, if at all possible, to see the time the message was delivered and read.

### Steps to reproduce
- receive a short message with linkable text such as “1am”
- attempt to view details of the message via swiping left or long pressing

**Actual result:** Cannot swipe or long press for info
**Expected result:** I would expect to be able to swipe right to left anywhere in the white space to the right of the message bubble instead of only being able to swipe within the bubble.

Alternatively, the iOS messages app has a nice feature: swiping from right to left anywhere on a thread view reveals a “drawer” on the right with time stamps of messages.

### Screenshots

Unfortunately I don’t see a way to upload screenshots from the GitHub mobile site as pasting images in a textarea doesn’t work in safari mobile.

### Device info

**Device**: iPhone 8
**iOS version**: 11.2.5
**Signal version:** 2.19.5.0

**Comment by leonardoporpora** [comment]
should be fixed in the latest release :) if it's not send us a debug log

**Comment by michaelkirk** [comment]
@leonardoporpora - that's not true, this is still an issue, and will likely remain an issue for a bit. There just isn't enough space to swipe the message off. Extending the swipe area could work, but could also surprise people since they're not swiping the message area.

Ultimately, we'll probably remove this gesture for incoming messages (we'll leave it for outgoing). But we don't want to do that yet because the information in the message details isn't currently accessible any other way.

When we surface the sent vs. received time in the conversation view like Android does (which we're working on), there will be no need for the message details screen on incoming messages, so eventually we can remove the gesture all together for incoming messages (again, it will remain for outgoing messages where the per-recipient details remain relevant).

**Comment by ejanalysis** [comment]
see issue #3347

**Comment by michaelkirk-signal** [comment]
We removed the swipe-left for info gesture long ago, so I'm closing this.
