### ISSUE TITLE
Unable to Share photo with phone in landscape mode 

### ISSUE THREAD

**Issue by stillalex** [signalapp/Signal-iOS#3066]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Trying to share photo while keeping the phone in landscape mode.

### Steps to reproduce
- use phone in landscape mode
- open photo app
- tap share
- choose Signal
- choose contact
- preview the photo
- can't send due to missing button

**Actual result:** preview in landscape mode does not show the bottom 'Send' button, I can only see the cancel icon

**Expected result:** be able to see the button so I can share the photo

Workaround is to flip the phone in normal mode (button will show) and then flip back to landscape, layout will adjust properly, button will be visible.

### Device info

**Device**: iPhone SE
**iOS version**: iOS 11.2.5
**Signal version:** 2.20.0.42

**Comment by TreatyOfRome** [comment]
Same behaviour is present when trying to share a freshly taken screenshot through Signal.

### Steps to reproduce
- take screenshot
- open screenshot app by tapping the lower left corner of the screen (the screenshot)
- tap share
- choose Signal
- choose contact
- preview the photo
- can't send due to missing button

No workaround possible (flipping to landscape doesn't work).

### Device info
Device: iPhone 5S
iOS version: iOS 11.2.5
Signal version: 2.20.2.2

**Comment by stillalex** [comment]
@TreatyOfRome I saw the same thing on my phone a few times, but could not reproduce reliably (sometimes it worked sometimes it didn't) so I thought maybe it's just me

**Comment by michaelkirk-signal** [comment]
I believe this has been fixed with iOS12, please reopen otherwise.

**Comment by erikstrottmann** [comment]
Still happens for me on iOS 12 when sharing a newly taken screenshot. Same as @TreatyOfRome’s comment above.

Device: iPhone 6s
iOS version: 12.1
Signal version: 2.30.2.16

**Comment by TreatyOfRome** [comment]
Issue persists on my phone as well.
Device: iPhone 6
iOS version: 12.1
Signal version: 2.31.0.39

**Comment by denver-s** [comment]
I have a similar issue:

- rotate iPhone to landscape mode
- open chat
- click "+" and click on camera button
- take a photo
- go to media composer, click on "Send" button

**What happens:** photo is sent (but you still don't know), but "Send" button disappears and there is no way you can close the composition view.
**Expected behavior:** composition view should close and show the sent photo.

**Screenshots:**
1. Signal chat in landscape mode

![image](https://user-images.githubusercontent.com/31325316/70647603-98cd4080-1c49-11ea-9603-35bf2c02e362.png)

2. Take a photo (buttons are not rotated to landscape mode!)

![image](https://user-images.githubusercontent.com/31325316/70647391-20667f80-1c49-11ea-9690-44fa8d69d41c.png)

3. Composition view: click "Send" button

![image](https://user-images.githubusercontent.com/31325316/70647444-3e33e480-1c49-11ea-901e-d43462ececd4.png)

4. Composition area disappears! Going back and clicking "X" does not close the composition view.

![image](https://user-images.githubusercontent.com/31325316/70647478-4e4bc400-1c49-11ea-8fd2-b4d5169ba095.png)

5. Force close the app, then open chat and see that message has been sent:

![image](https://user-images.githubusercontent.com/31325316/70647552-789d8180-1c49-11ea-98e0-1d8c51002867.png)


Debug log:
https://debuglogs.org/4b203ceece5f06c21bcddd97a8b75ec5fed8e6ffc39fec11c53b5cb274a80db9.zip

**Comment by Mihahn** [comment]
> I have a similar issue:
> 
>     * rotate iPhone to landscape mode
> 
>     * open chat
> 
>     * click "+" and click on camera button
> 
>     * take a photo
> 
>     * go to media composer, click on "Send" button
> 
> 
> **What happens:** photo is sent (but you still don't know), but "Send" button disappears and there is no way you can close the composition view.
> **Expected behavior:** composition view should close and show the sent photo.
> 
> **Screenshots:**
> 
>     1. Signal chat in landscape mode
> 
> 
> ![image](https://user-images.githubusercontent.com/31325316/70647603-98cd4080-1c49-11ea-9603-35bf2c02e362.png)
> 
>     1. Take a photo (buttons are not rotated to landscape mode!)
> 
> 
> ![image](https://user-images.githubusercontent.com/31325316/70647391-20667f80-1c49-11ea-9690-44fa8d69d41c.png)
> 
>     1. Composition view: click "Send" button
> 
> 
> ![image](https://user-images.githubusercontent.com/31325316/70647444-3e33e480-1c49-11ea-901e-d43462ececd4.png)
> 
>     1. Composition area disappears! Going back and clicking "X" does not close the composition view.
> 
> 
> ![image](https://user-images.githubusercontent.com/31325316/70647478-4e4bc400-1c49-11ea-8fd2-b4d5169ba095.png)
> 
>     1. Force close the app, then open chat and see that message has been sent:
> 
> 
> ![image](https://user-images.githubusercontent.com/31325316/70647552-789d8180-1c49-11ea-98e0-1d8c51002867.png)
> 
> Debug log:
> https://debuglogs.org/4b203ceece5f06c21bcddd97a8b75ec5fed8e6ffc39fec11c53b5cb274a80db9.zip

Can't reproduce in 3.4.0.7. Do you still have this issue?
