### ISSUE TITLE
Screen lock is not enforced when a new message is available.

### ISSUE THREAD

**Issue by LogalDeveloper** [signalapp/Signal-iOS#3222]
- [x] I have searched open and closed issues for duplicates.
----------------------------------------
### Bug description
If you open the app when screen lock is enabled while it has a new message available, then the screen lock is not enforced.

### Steps to reproduce
- Open app normally. Notice the screen lock works fine.
- Get a friend to send a message to you.
- Now open the app again normally or by touching the notification. Notice the screen lock is not enforced.

**Actual result:** Screen lock is ignored when a new message is received.
**Expected result:** Screen lock to always be enforced whenever the app is opened.

### Device info
**Device**: iPhone 7
**iOS version**: 10.3
**Signal version:** 2.23.0.14

**Comment by michaelkirk-signal** [comment]
I can't reproduce this.

Since you filled out the issue template (thanks!) I can see you don't have Face ID, but might be using FaceID.

Keep in mind, we re-use biometric auth if it *just* happened. So if you've just unlocked your phone with your thumb a few seconds before, we don't redundantly ask you again when launching Signal.

To test this, next time you receive a message, unlock your phone with the opposite hand and see if you can reproduce the behavior you're describing.

This is intended behavior, and I believe it's the correct behavior in the overwhelming majority of cases. If you've authenticated just moments before, why show a redundant auth screen? That sort of user friction will only cause people to disable this feature, while offering no practical benefits.

I'm closing this, but please re-open if this doesn't cover what you're experiencing.

**Comment by LogalDeveloper** [comment]
This doesn’t quite cover what I’m experiencing. I can understand if I’m opening a message on the lock screen and I use my Touch ID once so that Signal doesn’t ask a second time, but the issue I’m seeing is I can have the phone open for a long time and it ignores the screen lock the moment it has a notification.

If my phone is already unlocked, I can open Signal all I want and the screen lock is enforced. However when it gets a notification, it just disregards screen lock and then starts enforcing again after once I’ve read the message.

**Comment by michaelkirk-signal** [comment]
So, to flush out your steps a bit...

0. Switch hands so as not to inadvertently auth with TouchID
1. Device is unlocked
2. Launch Signal
3. See screen lock (as expected)
4. Cancel alert, hit home button  (with non TouchID hand!)
5. You're no on your iOS home screen
5. Receive message, see banner alert at the top of your phone
6. Tap banner
7. Signal launches and you see the Signal inbox without the lock screen

Can you verify that you can reproduce using those exact steps, or if I've got the steps wrong, please update them.

**Comment by michaelkirk-signal** [comment]
Also please submit a debug log right after you experience this behavior.

**Comment by LogalDeveloper** [comment]
Those steps replicate what I’m getting. I’ll provide a debug log and possibly a small video demonstrating the behavior in a couple hours when I’m at my main computer.

**Comment by michaelkirk-signal** [comment]
Fixed in #3235, thanks for the report

**Comment by LogalDeveloper** [comment]
That pull request did not fix the issue. However, I noticed #3246 was recently merged, so I’ll wait until I test the next update before reopening this issue.

**Comment by LogalDeveloper** [comment]
The latest update pushed today has fixed the issue.
