### ISSUE TITLE
Message bubble not rounded in grouping

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#4054]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending another message after a first one the first message bubble is not rounded accordingly.

### Steps to reproduce
- Send a message
- Send another one without being interrupted by the receiver so the two messages are grouped visually.

**Actual result:** The first message is not visually grouped with the second one.

**Expected result:** The first message lower corner on the right should have a smaller radius.

### Screenshots

![message-not-roundet](https://user-images.githubusercontent.com/5073538/48791549-e054f780-ece9-11e8-9043-8ef45709c3d0.png)

### Device info

**Device**: iPhone 5

**iOS version**: 10.3.3

**Signal version:** 2.32.0.13 beta

### Link to debug log

https://debuglogs.org/ecebd3ec1d915b38b1eae2027e58aafdd1ac503a0de9731e8225ec58fd7cb6ee.zip

**Comment by tzs1** [comment]
Seems to be fixed (https://github.com/signalapp/Signal-iOS/commit/6cc28bdf8fb5a792fd2b7d106afdedf68f6ff628).

**Comment by michaelkirk-signal** [comment]
Thanks for reporting, this is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by denver-s** [comment]
I am still having issues with this. I might be related to the “new messages” divider.

Before:
![7A34272D-1443-40B2-9A40-DF08C9D45050](https://user-images.githubusercontent.com/31325316/56467881-f5fb5400-6424-11e9-85c9-524995fa8a61.png)

After:
![EDC0A4D7-E669-42B4-AE1C-AE23FCBF6ED8](https://user-images.githubusercontent.com/31325316/56467880-f5fb5400-6424-11e9-9d73-12b8fa2babe9.png)

https://debuglogs.org/b974d6d251c8c9985a433612aecdfe2bf714efb67e355cff959ed239bc49347c.zip
