### ISSUE TITLE
Status bar changes to black in dark theme

### ISSUE THREAD

**Issue by Raghul-S-1994** [signalapp/Signal-iOS#4159]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
 With black theme enabled, the status bar turns black when the audio record error message "Voice Message - tap and hold to record a voice message" is shown and remains  black until any further screen action is made

### Steps to reproduce
- Open signal
- Enable Dark theme (night mode)
- Open a conversation
- Make sure the status bar(one that shows time and carrier info) is white
- Now tap the audio icon
- Signal will show a warning message  
- Now the status bar will change to black

**Actual result:** The status bar turns to black making it invisible in the dark theme

**Expected result:** The status bar should stay white

### Screenshots

Expected:
![signal_status_bar_white_1](https://user-images.githubusercontent.com/20701077/54731193-de754500-4bb2-11e9-82c4-859c8dba1658.jpeg)

Actual:
![signal_audio_error_message_1](https://user-images.githubusercontent.com/20701077/54731208-f64cc900-4bb2-11e9-99c2-7fba9da934f2.jpeg)

Actual:
![signal_status_bar_black_1](https://user-images.githubusercontent.com/20701077/54731210-f947b980-4bb2-11e9-9730-e4072553e70b.jpeg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.1.4

**Signal version:** 2.37.2.0 (beta)

**Comment by tzs1** [comment]
Related to #4085 and #4130
This happens also when you want to send a photo.

**Comment by denver-s** [comment]
This has been probably fixed in 3.0.0.2

**Comment by denver-s** [comment]
Fixed (version 3.1.0.13).

**Comment by muellermartin** [comment]
This issue still exists when the Screen Lock functionality is enabled with the the dark theme. When Signal asks for Touch ID verification via a modal dialogue (similar to previously in the voice message) the status bar text switches to black and stays black until the UI gets redrawn (e.g., when a conversation is selected or the app is reopened).

![signal-status-bar-text-color](https://user-images.githubusercontent.com/343302/72033571-f4afd700-3292-11ea-82ee-e87ae4c1ede9.gif)
