### ISSUE TITLE
Chat opened from notification is not scrolled to bottom

### ISSUE THREAD

**Issue by igorkulman** [signalapp/Signal-iOS#4186]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When you open a chat from a push notification, the list of messages is not scrolled to bottom the same way when you open a chat from the main screen

### Steps to reproduce
- Receive a push notification for a new message in a chat
- Tap the notification so Signal opens showing the chat

**Actual result:** The chat should is not scrolled to bottom but to some place above or in the middle of the latest message

**Expected result:** Chat scrolled to the bottom the same way when you open a chat from the main screen

### Device info

**Device**: iPhone 6S

**iOS version**: 12.2

**Signal version:** 2.38.1

**Comment by philshem** [comment]
I think this is a duplicate of this issue: https://github.com/signalapp/Signal-iOS/issues/4185

Is it all chats, or group chat only?

Is there any messages about verifying safety numbers?

**Comment by igorkulman** [comment]
Definitely not a duplicate, this happens to me in 1:1 chats, no verifications messages displayed.

**Comment by philshem** [comment]
I suspect it’s related, and the big can occur under various conditions. Let’s see what the devs say.

**Comment by drozzy** [comment]
Same issue. Signal never remembers the place the conversation was. 
This started happening since a few updates ago.

**Comment by seveke3** [comment]
Same issue here. Only it happens just in 1 chat (group) and all the time, also if I open it with the app (not the notification). All the other chats don’t have that problem (group and individual).

**Comment by drozzy** [comment]
Seems to have been fixed **after** I deleted the mid-chat system notification of the verification code change.

**Comment by thegesuser** [comment]
Same issue. 
And when trying to scroll to that new message, it jumps to 5-6 messages above.

**Comment by blapcity** [comment]
Still having this issue. My OS and app are all updated. I've also tried reinstalling.
