### ISSUE TITLE
No audio in video messages

### ISSUE THREAD

**Issue by NJDeb** [signalapp/Signal-iOS#4196]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
NO SOUND WHEN RECORDING VIDEO

### Steps to reproduce
- GO TO CAMERA
- ANNOYINGLY NOW HAVE TO HOLD THE RECORD BUTTON TO RECORD VIDEO (PLEASE PLEASE PLEASE GET RID OF THAT SHIT!!!!!!!!!)
- VIDEO RECORDS, BUT THERE IS NO AUDIO!! 
- SEND VIDEO ANYWAY, RECIPIENTS CAN NOT HEAR ANY SOUND EITHER 
- IF THE VIDEO IS LONGER THAN A FEW SECONDS, IT SAYS “RECORDING STOPPED” AND THERE IS NO VIDEO AT ALL TO SEND 😡

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behavior)
See above

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)
THERE SHOULD BE AUDIO IN THE VIDEO AND THERE ISN’T ANY!!

### Screenshots

Screen shots are useless in this matter

### Device info

**Device**: iDevice X

iPhone XS

**iOS version**: X.Y.Z

12.3

**Signal version:** Z.Y

2.39.0.14

### Link to debug log

https://debuglogs.org/83914efbeaa0a53fef80e70e3585be39f7c99f0449ded588b0a35c55f47d6ec0.zip

-->

**Comment by michaelkirk-signal** [comment]
Hi @NJDeb - thanks for reporting that the latest release seems to have broken something for you.

Just to be sure - could you send me a screenshot of your app privileges? It's in the Settings app > Signal

**Comment by michaelkirk-signal** [comment]
One other thing to verify, could you capture a video from the same device using the native Camera app and then use Signal to send that to your friend. 

Are they able to hear that audio?

**Comment by zigg** [comment]
@michaelkirk-signal I've been experiencing this problem and I think I have detected a pattern and have a little more information.

1. It seems that if I record a video of ten seconds or less inside Signal, using the screen-side camera, it has sound.

2. It seems that if I record a video of twenty seconds or more inside Signal, same camera, it does not.

3. If I record and send any video with the native Camera app, it has sound.

You can detect the missing sound without sending a video just by playing it back within the Signal camera flow.

Microphone and Camera permissions are both present.

I'm on the Testflight betas and I'm using version 2.4.0.15.

**Comment by NJDeb** [comment]
Yea, same issue and I still have it. Sometimes I also go to record a video using the Signal app that’s only 5-10 seconds and I get a message saying it didn’t record. 🙄 
This new camera really is a poor change. Holding the button to record a video also majorly sucks. 
Why can’t they just restore the previous camera version for iPhone users??? It’s like they attempted to “fix” something that wasn’t broken and broke it!

**Comment by michaelkirk-signal** [comment]
@zigg - thanks for the followup! We have a fix coming soon.

**Comment by michaelkirk-signal** [comment]
The fix is available in 2.39.2.0 or later, available in the appstore now.

**Comment by zigg** [comment]
@michaelkirk-signal Real quick, is there or will there soon be a Testflight version that has this fix?

**Comment by shanduur** [comment]
The issue is still present, Signal 6.24.0.9 on iOS iOS 16.4.1 (a) (20E772520a)
