### ISSUE TITLE
[video call] no display rotation

### ISSUE THREAD

**Issue by andyggg** [signalapp/Signal-iOS#4239]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During a video call, the screen will not rotate when turning the iPhone from portrait to landscape orientation. 

### Steps to reproduce
- start a video call with someone (in portrait orientation)
- turn the iPhone to landscape 

**Actual result:** the video of your partner does not rotate correspondingly. Thus, your conversation partner is not displayed upright but 90° turned. 

**Expected result:** the video of your partner should be rotated in correspondence with the orientation of the iPhone.

Note: interestingly, the tiny video of yourself that is taken by the front camera is rotated correctly.

### Device info
**Device**: iPhone X, iPhone Air 2

**iOS version**: 12.4

**Signal version:** 2.41.0.21

**Comment by rbaker2019** [comment]
Can confirm this bug persists in the current stable version on the app store.

**Device**: iPhone XR    
**iOS version**: 13.3.1    
**Signal version**: 3.6.1.4

**Comment by ElCoffee** [comment]
For debuging purposes: it seems that if you start a call when your phone is already in landscape mode, the video call will be in landscape.

**Comment by zhsnv** [comment]
The issue is still here on the iPad app. People tend to use the iPad in horizontal orientation. However, video calls are not rotated. I have contacted the support service a couple of days ago and haven’t heard anything yet.

**Comment by metal3d** [comment]
Problem still present on Android version - didn't checked the beta version yet

**Comment by Brigitte13e** [comment]
Almost 2 years later and this is still an issue. That this isn’t solved or maybe even build yet bothers me a lot because this is the main reason why people in my network stop using Signal after a test period.

**Comment by zhsnv** [comment]
> Almost 2 years later and this is still an issue. That this isn’t solved or maybe even build yet bothers me a lot because this is the main reason why people in my network stop using Signal after a test period.

It boggles my mind how this issue still a thing. Previously, I’ve commented that this is an iPad issue, however, I’ve later found out that this issue is present on PC as well.

**Comment by Brigitte13e** [comment]
I discovered the next during a test video call between an iPhone and an Android phone:

On my iPhone during a video call when I rotate, nothing in Signal will rotate. I think this means Signal on iOS doesn’t support rotation at the moment (from portrait mode to landscape mode and vice versa).
On my Android phone during a video call when I rotate, all the buttons will rotate simultaneously. Also my own video preview jumped to the right corner. Only the incoming video won’t rotate with me and stays the same. Result: Only the incoming video is in the wrong direction when I rotate my phone.

**Comment by davidchisnall** [comment]
Rotating the phone does appear to rotate the outgoing video (it switches from portrait to landscape for the remote person) but not the incoming video (remote people are shown on their side).

**Comment by anonymouscowhead** [comment]
Issue still happens in Aug 2021, on a video call between iPad and Android phone.  On the iPad (nearly always used in portrait) the video preview looks fine, then when the call starts, it rotates 90 degrees.   Agree with Brigitte13e that this is one of those little annoyances that gets people who are trying out Signal to move on keep looking for other alternatives.

**Comment by davidchisnall** [comment]
I believe this is fixed now.

**Comment by anonymouscowhead** [comment]
It is much better than it was to the point where I can use it without being annoyed, although not 100% perfect:
1. I tested a video call between iPhone and Android.  It's right if both people hold their phone the same way.  If one holds vertically and the other horizontally, it is messed up.
2. I tested a video call between iPad and Android, and oddly it behaves slightly differently then:  The Android user can rotate in any direction and the image on the iPad is rotated to look sensible.. but if the iPad user rotates, they look sideways on the Android phone screen.

**Comment by lajawi** [comment]
I have come across this issue while searching for it, and am sad to say this is a problem still/again in the current latest version of Signal.

No matter the orientation of the iPhone, the other people's cams don't rotate accordingly. My camera however rotates correctly and does appear correct on other's phones.

**Comment by MagdalenaPolac** [comment]
Same problem- iOS 26.0.1, Signal 7.82 (1102)
