### ISSUE TITLE
[BUG] "Jumping" conversations

### ISSUE THREAD

**Issue by Mihahn** [signalapp/Signal-iOS#4402]
### Bug description
When you open a (long) conversation and scroll up to see old messages, the conversation "jumps" to messages sent/received a few hours or even days ago. This is discussed in Signal forums since 3.1 I guess but I couldn't find it documented on Github.

### Steps to reproduce
- Open a conversation
- Scroll up to see old messages

**Actual result:** Signal jumps to messages far above

**Expected result:** Signal should scroll messages continuously

### Device info
**Device**: iPhone 7
**iOS version**: 13.4
**Signal version:** 3.6.0.7

**Comment by michaelkirk-signal** [comment]
Thanks for the report!

This was partially fixed with 3.6, but we found another repro with similar symptoms which will be fixed when 3.7 is released.

**Comment by denver-s** [comment]
@Mihahn this should be fixed now in 3.7.0.9

**Comment by Mihahn** [comment]
Still not fixed for me in 3.7.0.9. It may have improved - but it's still not fixed, especially not while scrolling up fast in large conversations.

**Comment by 211217613** [comment]
Still present even on 3.7.0.10 @michaelkirk-signal 

Not as often as on 3.6

**Comment by denver-s** [comment]
@Mihahn @211217613 I am not experiencing this issue anymore, are you?

**Comment by Mihahn** [comment]
@denver-s looks like it's fixed for me – I'll close this issue now. Thank you for the reminder!
