### ISSUE TITLE
Can not add new contact to group

### ISSUE THREAD

**Issue by hundehausen** [signalapp/Signal-iOS#4466]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can not add new contact to group. 

### Steps to reproduce
- add new contact to my existing group (I am admin)

**Actual result:** Error message: contact already member of group

**Expected result:** Contact adds to group

### Device info
**Device**: iPhone 11 Pro

**iOS version**: iOS 13.5

**Signal version:** 3.9.0.13

**Comment by AlpacaFur** [comment]
I have the same issue (iOS 13.3.1, iPhone 7, Signal 3.9.0.13)

**Comment by demakarim** [comment]
I’m having the same issue as well (iOS 13.3.1, Signal 3.9.0.13, iPhone 7). I created a group three times, all three times I have tried to add people after the group is created, it says “user already in group” but the users aren’t in the group and don’t even show up on the member list. I have tried reinstalling signal and it still doesn’t work.

**Comment by Pingmin** [comment]
Me too!

(iOS v13.5, iPhone SE v1, Signal v3.9.0.13)

**Comment by Imperiopolis-Signal** [comment]
This is fixed in the 3.9.1 build that went out early today, thanks for reporting it!

**Comment by meet2kamal** [comment]
Still see this issue on
device - iPhone 11
OS version - 14.3
Signal application software version - 5.1.0.31

**Comment by sneko** [comment]
@Imperiopolis-Signal got this with latest Signal version.

Can this be reopened?

**Comment by sneko** [comment]
As requested on the Desktop issue https://github.com/signalapp/Signal-Desktop/issues/4314#issuecomment-1210950063 I commented on:

# Adding him a new time when invitation already sent but he cannot accept

Here is the debug logs:
https://debuglogs.org/ios/5.47.0/8883ee39c101ac0d1bb4096a89d6b1f3303868b8ab64b5c9b7a5a2343ca8579b.zip

With a screenshot when trying to add it a new time to the group (he is not able to accept as mentioned his case in https://github.com/signalapp/Signal-Android/issues/12383):
![IMG_4546](https://user-images.githubusercontent.com/8195958/184140902-3285c991-15ff-4ecd-90c0-71375050f54b.jpg)

# Creating a brand new group with him as member

Here is the debug logs:
https://debuglogs.org/ios/5.47.0/ca8aa4abafab381b479f8a7010034ecb51dee3dbd3b017db5d270f1af04d69c0.zip

Screenshot:
![image](https://user-images.githubusercontent.com/8195958/184142653-dcac537f-6969-4f4b-9f52-4463e50d1ccb.png)
