### ISSUE TITLE
PIN creation fails

### ISSUE THREAD

**Issue by 2600box** [signalapp/Signal-iOS#4468]
I have updated twice now. Currently on 3.9.0.13

PIN creation fails no matter what I do.

https://debuglogs.org/499ee7e0d5ea65a08b0c1e4eb79c999ede121a29f402ef6416b2c6de1efc391e.zip

**Comment by Imperiopolis-Signal** [comment]
We just started rollout of 3.10 which should resolve these issues.

**Comment by 2600box** [comment]
Updated to 3.10.0.8. Same issue.

https://debuglogs.org/20a3ee34e4ef92ac51860f9ded5eb07190921f1925c0b31d365374a20a1c8fc5.zip

**Comment by Imperiopolis-Signal** [comment]
Okay, I'm sorry it didn't resolve your issue. Is your device perhaps behind a VPN or firewall that might be interfering with communication to api.backup.signal.org ?

**Comment by 2600box** [comment]
It seems so, though I have tried wifi and cellular. 

This is what curl shows. Is this normal?

curl -vp https://api.backup.signal.org/
*   Trying 52.168.69.235:443...
* TCP_NODELAY set
* Connected to api.backup.signal.org (52.168.69.235) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by Imperiopolis-Signal** [comment]
We just released a 3.10.1 build, could you please try again and provide your logs?  I don't expect it to be fixed, but I addef additional logging that should aid us in tracking this down

**Comment by sg25dev** [comment]
I am not having the same issue as described but I am also having SSL related errors trying to connect to this site.  Same exact Curl output as reported by 2600box.  Also, when trying to access the site using Chrome

NET::ERR_CERT_AUTHORITY_INVALID

api.backup.signal.org normally uses encryption to protect your information. When Google Chrome tried to connect to api.backup.signal.org this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be api.backup.signal.org, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit api.backup.signal.org right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

I am not behind any VPN or Proxy.

<img width="1064" alt="screenshot" src="https://user-images.githubusercontent.com/44074893/86040840-b65dce00-ba12-11ea-98c8-b0a7dfe9c912.png">

**Comment by u32i64** [comment]
> @sg25dev 
> I am not having the same issue as described but I am also having SSL related errors trying to connect to this site. [...]
> NET::ERR_CERT_AUTHORITY_INVALID
> 
> api.backup.signal.org normally uses encryption [...]

This error is expected when you're trying to connect *"normally"*. See Moxie's blog post [Your app shouldn't suffer SSL's problems](https://moxie.org/2011/12/05/authenticity-is-broken-in-ssl-but-your-app-ha.html) for why.

**Comment by sg25dev** [comment]
> > @sg25dev
> > I am not having the same issue as described but I am also having SSL related errors trying to connect to this site. [...]
> > NET::ERR_CERT_AUTHORITY_INVALID
> > api.backup.signal.org normally uses encryption [...]
> 
> This error is expected when you're trying to connect _"normally"_. See Moxie's blog post [Your app shouldn't suffer SSL's problems](https://moxie.org/2011/12/05/authenticity-is-broken-in-ssl-but-your-app-ha.html) for why.

Thanks for this.

**Comment by dn4hc** [comment]
I’m getting the same issue. 

![6977014A-3F4A-40D7-A75D-2B5E5E44085C](https://user-images.githubusercontent.com/3523129/86818843-3a2a5100-c0ca-11ea-9887-228a030d3d5e.png)

**Comment by Imperiopolis-Signal** [comment]
Thanks, this log contains some really helpful information that will hopefully get us to the bottom of this issue.

**Comment by Imperiopolis-Signal** [comment]
This issue is now fixed on our 3.13 beta. If you could send debug logs after confirming it's fixed, it would provide us some very useful information. You can join the beta [here](https://testflight.apple.com/join/8FHtd1Jq).

**Comment by mkolassa** [comment]
I can confirm that v3.13 in TestFlight resolves the PIN creation issue for me. 

Here is the debug log that you requested. 

https://debuglogs.org/8a0cc48a528fa572c4381dd6d4f20f0c582adfe18e328753ba968370f77f9634.zip

**Comment by jtressle** [comment]
FYI, Still appears to be broken in 3.21.0.10. Just downloaded the app. 

Thanks

![798C9371-D1DD-4B00-975E-74EC33256F9C](https://user-images.githubusercontent.com/13778165/97828742-d6c9bd80-1c7c-11eb-948c-474cdd729b10.png)

**Comment by jtressle** [comment]
Update: it worked when I disabled my WiFi and used cellular!  

Thanks

**Comment by littl3rud3** [comment]
> This issue is now fixed on our 3.13 beta. If you could send debug logs after confirming it's fixed, it would provide us some very useful information. You can join the beta [here](https://testflight.apple.com/join/8FHtd1Jq).

Hey, i just registered an acc and can’t set the pin. There said “PIN creation failed. Wifi/cellular had the same result. Also no VPN. 
Hardware: iPhone 
HID: 13,4 
iOS Version: 14.3 (18C66) 
Signal Version: 5.2.0.4 
Log URL: https://debuglogs.org/d4a3413275681526951890727a89be23db56aee475eaa1a8e5cc00bf007cf479.zip 
Locale: en_RU

**Comment by rdeits** [comment]
I'm getting the same issue (or, at least, the same generic error message) with Signal 5.2.3. My system info is below, and I've submitted a debug log through the internal help function already:

```
Time          : 1611545655410
Manufacturer  : Google
Model         : Pixel 3a
Product       : sargo
Screen        : 1080x2088, xxhdpi (440), 60.00 hz
Font Scale    : 1.0
Android       : 11 (6985033, RQ1A.210105.002)
ABIs          : arm64-v8a, armeabi-v7a, armeabi
Memory        : 35M (61.10% free, 512M max)
Memclass      : 192
OS Host       : abfarm-01365
Censored      : false
Play Services : true
FCM           : true
Locale        : en_US
Linked Devices: false
First Version : 772
Days Installed: 0
App           : Signal 5.2.3 (772, 77202)
Package       : org.thoughtcrime.securesms (doDiFGKPO1r)
```

I've already tried uninstalling and reinstalling Signal and creating both an alphanumeric and a purely numeric PIN.

**Comment by DonatoClun** [comment]
Same problem here.
V. 5.3.7.1
Both on wifi and 4G. No VPN.
Tried numeric and alphanumeric pin.

In the log I found a SSLException
"I/O error during system call, Software caused connection abort."
which seems to be related with the issue.

**Comment by marilou000** [comment]
We have a number of beneficiaries that is encountering the issue of setting a PIN.
This is a matter of security for at risk users.

**Comment by thegranddesign** [comment]
This is still a problem.  When is this going to be resolved?

**Comment by parraline5750** [comment]
Really? Year and a half later and nothing? Couldn't restore when I moved phones, can't set a PIN to secure a supposedly secure app? No wonder Telegram is wrecking shop.

**Comment by 5oundless** [comment]
Is this issue actively being worked on? I was going to transfer to another device, but had issues with the PIN. Then I found this issue on GitHub. Should we just move on with the assumption that PINs won't work for an undetermined amount of time? Has it ever worked?

**Comment by phatina** [comment]
I confirm, this happens to me using either wifi, mobile data. Shall we reopen this issue? :thinking:

**Comment by thegranddesign** [comment]
I guess that's one way to "solve" an issue :roll_eyes:
