### ISSUE TITLE
3.9.1 heat and battery drain on iPhone 8

### ISSUE THREAD

**Issue by DrFleischman** [signalapp/Signal-iOS#4471]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm running Signal on my iPhone 8 iOS 13.5.1.  Starting yesterday (June 2, 2020), after I updated to 3.9.1, I noticed my phone overheating and rapid battery drain whenever I have Signal in the foreground.  The problem appears to go away when I switch off Signal but it's still running in the background.  Neither shutting down Signal (double-press home button, swipe up) nor phone restart solves the problem: As soon as I start Signal back up and have it in the foreground, the problem comes back.  I don't need to use the camera or anything non-standard.  This is just regular texting back and forth.

### Steps to reproduce
- Run 3.9.1 in the foreground

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Hot phone, very fast battery drain.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Normal temperature phone, normal battery drain

### Screenshots

N/A

### Device info

**Device**: iPhone 8

**iOS version**: 13.5.1

**Signal version:** 3.9.1

### Link to debug log

https://debuglogs.org/46c7175e524a7bb43f2a1cf15af5b6b55f5f3c9844562b6a9d14039bc5c84d10.zip

**Comment by dvelyk** [comment]
I too have this problem on an iPhone SE.

### Device info

**Device**: iPhone SE

**iOS version**: 13.4.1

**Signal version**: 3.9.1.1

**Comment by rswoop8** [comment]
I am having the same issue on an iPhone X, albeit only in one of my conversations; having the conversation list or any other conversation open does not cause the issue. I profiled the phone using the Instruments app on my Mac, and it shows Signal's CPU usage as anywhere between 70% - 100% while the conversation in question is open.

### Device info

**Device**: iPhone X

**iOS version**: 13.5.1

**Signal version**: 3.10.0.8

**Comment by glomeg132** [comment]
I'm having the same problem on my iPhone 11 pro. With almost no usage Signal took 14% in 9 hours in the background.

Device info

Device: iPhone 11 pro

iOS version: 13.5.1

Signal version: 3.9.1.1

**Comment by matthesjh** [comment]
I'm having the same problem too. When a conversation is open, the battery drains very fast and the device becomes very hot.

### Device info

**Device**: iPhone 8

**iOS version**: 13.5.1

**Signal version**: 3.10.1.1

**Comment by Fluxkomqensator** [comment]
I also have the problem. When a conversation is open I can literally watch the battery percentage going down. Phone gets hot. Battery fall seems to stop in conversations/contacts overview. 

**Device info**
**Device:** iPhone SE
**iOS version:** 13.5.1
**Signal version:** 3.10.2.1

**Comment by DrFleischman** [comment]
A follow up, I updated to Signal version 3.10.1 and then 3.10.3, and the problem persists.

**Comment by Bee-ble-brox** [comment]
Updated to 3.10.5.3 ans the problem persists. Just lost 13% battery in 30 minutes… :/

**Comment by Cerberus0** [comment]
@dvelyk, @rswoop8, @matthesjh, @Fluxkomqensator, @Bee-ble-brox: If you could share debug logs, that could help the developers diagnose this issue sooner:

* https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug

@DrFleischman, @Bee-ble-brox: Please do not [bump issues](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#dont-bump-issues). It's safe to assume that the problem will persist until this issue is closed.

**Comment by Imperiopolis-Signal** [comment]
In addition to capturing debug logs, can you please cite the time range in which you were seeing the heat issues so we can correlate with the logs? Also any other context for what you were doing at the time would be helpful. We’ve had a very difficult time reproducing this behavior.

**Comment by rswoop8** [comment]
Debug log linked below

Steps I took to produce this log:
- Enable debug logging
- Exit settings, open problematic conversation
- Allow the phone to sit for a few minutes, until its temperature has increased notably
- Navigate back to settings, get link to debug log

The log appears to be relatively empty, as all I am doing is opening the problematic conversation and allowing the phone to sit for a few minutes. Is there anything I can do to hopefully provide some more detailed logs/info?

https://debuglogs.org/c369119635e7249e070e74d5a74387a0ea344ebdb1b1bb04ebf4712c8249395d.zip

**Comment by mortoray** [comment]
I have the same problem on iPhone 7. This started happening about 2 weeks ago, roughly after one of the recent Signal updates.

**Comment by 211217613** [comment]
This is for the heat issue. I was on a call via Airpods and my iPhone had to shut itself down. Had a black screen and temperature warning.

Device info
Device: iPhone 8
iOS version: 13.4.1
Signal version: 3.10.5.3

[e37afdf1facb5ef3cbf63ab2a3c6f10bc3898b9bf5f1e50fcce38325d1bf6bdd.zip](https://github.com/signalapp/Signal-iOS/files/4777342/e37afdf1facb5ef3cbf63ab2a3c6f10bc3898b9bf5f1e50fcce38325d1bf6bdd.zip)

**Comment by DXCanas** [comment]
Having the similar issues on my iPhone 11. Signal has been using most of my battery for at least the past 10 days (that’s as far as iOS battery stats go). For the past 2 or 3 weeks, I’ve noticed that I’ve had to charge much more often than before, but I didn’t check my battery stats until recently. 

On May 28, my phone also drained an incredible amount (about 20%-30%, iirc) over an hour and 17 minute long call. 

It’s getting to be pretty frustrating. 
https://debuglogs.org/d8e8057f5e2dfc7e014eaec5aec4661b615171439314a41fea504829f84f333e.zip

**Comment by guimspace** [comment]
@Imperiopolis-Signal You may check if the issue is related to how Signal currently switches from Wi-Fi to cellular (or vice-versa) - also the frequency and how easily it will switch; iPhone Wi-Fi assist could be playing a role here too. While having both enabled, the iPhone produces more heat (thus more energy consumption) than having one of two disabled. It is consistent for me and my partner.

**Comment by DXCanas** [comment]
Want to point out that others are describing similar issues on Reddit:
https://reddit.com/r/signal/comments/h96tq0/ios_battery_drain/

**Comment by hydraplumbinggroup** [comment]
Nothing conclusive so I won't be posting logs, but echoing others thoughts regardless. In the last 10 days or so I've noticed my phone requesting `Low Power Mode` at around 8-9pm, rather than typically ending the day on ~30%.

iPhone Xs 64GB - 13.5.x - Automatic Updates.

**Comment by adrianmace** [comment]
Nothing conclusive so I won't be posting logs, but echoing others thoughts regardless. In the last 10 days or so I've noticed my phone requesting `Low Power Mode` at around 8-9pm, rather than typically ending the day on ~30%.

iPhone Xs 64GB - 13.5.x - Automatic Updates.

**Comment by matthesjh** [comment]
This problem seems to be fixed with the latest production version **3.12.0.16**. I just opened a conversation which previously resulted in some overheating and battery drain after some minutes, and now everything is fine after ten minutes.

**Comment by swotam** [comment]
Same issues here on an iPhone 11 Pro Max and an iPad Pro 9.7". Issue started within the last month following one of the Signal iOS app updates. Battery use and overheating is through the roof and isn't acceptable. For the time being, Signal isn't going to be used on my devices, I'll just switch to an alternative and may not return. 🖖

**Comment by rswoop8** [comment]
Problem also appears to be fixed for me as well (app version 3.12.0.16). Phone no longer gets hot when opening the previously problematic conversation, and CPU usage while said conversation is open is now back on par with all the other conversations (5% - 8%). Thank you to the Signal devs for fixing the issue; can't have been an easy one to track down.

**Comment by Imperiopolis-Signal** [comment]
We’re glad to hear this is fixed!

**Comment by iHarryme** [comment]
Is it fixed? I mean look at this. 
![8CE77E22-374E-4BAA-BBA3-C40C543B4F98](https://user-images.githubusercontent.com/45716271/86080647-07240400-bab1-11ea-8fc2-debf5c4eed0f.jpeg)
![87CF0A35-21F8-4EA6-B278-F989FAE79230](https://user-images.githubusercontent.com/45716271/86080650-09865e00-bab1-11ea-999c-e90b007b67f2.jpeg)
It still consumes nearly 20% for less than two hours of usage (1 and half hours of it is background activity, what ever that means) here is the debug log 
https://debuglogs.org/6292bb1abc8ac509c289642f9ea8775d1fc62b67b84e4da22b61ecfe10f37cbf.zip

**Comment by DXCanas** [comment]
Can confirm, still getting the issue. Gave it a few days to be sure. 

https://debuglogs.org/99e5e69607d6b70a6a10d3ce2699849406c26f9ab6932b51ead573c4ac584a2e.zip

See disproportionate battery use relative to screen time

![843EF59D-9E5D-4746-906A-73FDB57D1C44](https://user-images.githubusercontent.com/9877852/86313346-bcea7200-bbd9-11ea-8c6b-ec0e6ce0552a.jpeg)
![5FF6ED48-9730-48DA-BF8E-3A2540B724CE](https://user-images.githubusercontent.com/9877852/86313356-c07df900-bbd9-11ea-858a-5ab3de7d42cb.png)

**Comment by DXCanas** [comment]
Can confirm, still getting the issue. Gave it a few days to be sure. 

https://debuglogs.org/99e5e69607d6b70a6a10d3ce2699849406c26f9ab6932b51ead573c4ac584a2e.zip

See disproportionate battery use relative to screen time

![33745624-2F1C-438F-8E52-ADDB35FE9D3F](https://user-images.githubusercontent.com/9877852/86313645-83663680-bbda-11ea-9cf1-3198e8303fe7.jpeg)
![3C157432-6EE6-46E4-B258-1066319D3E0E](https://user-images.githubusercontent.com/9877852/86313652-85c89080-bbda-11ea-9d90-9b88e6111081.jpeg)

**Comment by iHarryme** [comment]
https://github.com/signalapp/Signal-iOS/issues/4496
Opened an issue.

**Comment by tomiteko** [comment]
I’m still having the issue
iPhone SE 2020
iOS 13.5.1
Signal 3.12.4.1

**Comment by DXCanas** [comment]
Checking in after latest update - same behavior. 

Might this have to do with just having really long conversations?

https://debuglogs.org/16936008659db11a1641e10fe05979851a51b20b6eb868ff867e180898d8c45d.zip

Pinging #4496 here, because this issue is older.

**Comment by 211217613** [comment]
Ya I can confirm that I'm still seeing overheating on the phone when making  calls. Is there any way to get device or cpu temperature metrics in the debug logs for signal?

**Comment by philnord** [comment]
I have an iPhone X and using 3.17, installed everything yesterday. I get this issue as well and only have 5 contacts and no group chats. Signal using a lot of battery.
