### ISSUE TITLE
Signal disappeared from iOS share bottom sheets

### ISSUE THREAD

**Issue by LeoniePhiline** [signalapp/Signal-iOS#4862]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal disappeared from iOS share bottom sheets after agreeing to allow the "share directly to conversations" feature.

**Steps:**
E.g. in the photos app, tap share. Previously Signal was an app on the list.

**Previously/Context:**
Yesterday, Signal showed me a confirmation dialog, asking me if I want to show conversations in the share view (like iMessage and WhatsApp). I said Yes. 

**Actual result:**
Since then, Signal is no longer a share target app, and I still only have iMessage conversations at the top of the share sheet.

**Expected result:**
I want to see my (most recent / most frequented) conversations in the share sheet.

### Device info

**Device**: iPhone 11 Pro Max
**iOS version**: 14.4
**Signal version:** 5.3.2.1

**Comment by andrew2915** [comment]
I experienced this problem without answering the prompt about showing conversations in the sharing menu. I tried enabling and disabling it -- neither result in Signal being shown in the share menu.

**Comment by meyermarcel** [comment]
> I can confirm this bug in iOS Safari on my device. I encountered this bugs because two friends using Signal asked me to help because they also have a disappeared Signal share button in Safari.
> 
> It is possible that this really annoying bug originates from iOS. If iOS 14.5 solves this problem I think we should consider closing this issue.
> 
> ### Bug description
> **Steps:**
> 
> 1. Open Safari
> 2. Press share button
> 3. Press "More" in horizontal listed apps
> 4. Press "Edit"
> 5. Remove Signal with red minus sign
> 6. Disable Signal share button
> 7. Restart Safari
> 8. Disabled Signal share button is disappeared
> 
> **Previously/Context:**
> Editing share sheet in iOS Safari.
> 
> **Actual result:**
> Disabled Signal share button is completely disappeared. Restarting iPhone does not bring back the Signal share button.
> 
> **Expected result:**
> Signal share button should be there.
> 
> ### Device info
> **Device**: iPhone SE (1st generation)
> **iOS version**: 14.4.2
> **Signal version:** 5.8.0.22

The Signal share button in share sheets in Safari is back and share buttons from other third-party apps reappeared. So my problem was an iOS problem.

I have noticed the initial bug of @LeoniePhiline relates to the more advanced feature. This feature allows direct shortcut access to recently used chats. @LeoniePhiline Is this a correct description of the feature and does the bug still exist?

This issue could be related to #4625 

Additionally I found an official support document to ensure the correct settings in iOS: https://support.signal.org/hc/en-us/articles/360055765072-Show-in-Suggestions

**Comment by LeoniePhiline** [comment]
@meyermarcel I think you are experiencing a different bug, rooted within iOS, not the signal app.

>  Is this a correct description of the feature

What are you referring to? My description is correct, yours describes a different issue. Maybe we misunderstand each other. :)

The issue is no longer relevant for me, but it might be for others. For me, the separate conversations showed up after a while. I guess each one showed up after I had an interaction with the respective person within the signal app. But sharing to signal was not possible in this period.

Now, however, I do have separate signal conversations to share to, **and** I have the signal app to share to. I do not know, though, if this has accidentally showed up again ('fixed itself') or if the actual root cause was fixed in the signal source code.

**Comment by andrew2915** [comment]
It works for me now also. The share menu shows recent conversations I have in Signal and/or SMS, and below that are the list of apps including Signal and others.

**Comment by meyermarcel** [comment]
> @meyermarcel I think you are experiencing a different bug, rooted within iOS, not the signal app.
> 
> > Is this a correct description of the feature
> 
> What are you referring to? My description is correct, yours describes a different issue. Maybe we misunderstand each other. :)
> 
> The issue is no longer relevant for me, but it might be for others. For me, the separate conversations showed up after a while. I guess each one showed up after I had an interaction with the respective person within the signal app. But sharing to signal was not possible in this period.
> 
> Now, however, I do have separate signal conversations to share to, **and** I have the signal app to share to. I do not know, though, if this has accidentally showed up again ('fixed itself') or if the actual root cause was fixed in the signal source code.

Hey @LeoniePhiline,

I think so too that I have a different bug in mind. I chose the wrong issue for the bug I was experiencing.

Other topic:
If your reported bug no longer exists it would make sense to close this issue to help maintaining 600+ open issues. It is possible that new versions of Signal resolved this bug since the reporting in Signal version 5.3.2.1. If someone encounters that bug again there is always the possibility to open a new issue.

What do you think @LeoniePhiline @andrew2915 ?

Best regards
Marcel

**Comment by andrew2915** [comment]
@meyermarcel, I agree the issue should be closed because I think it has been solved. It hasn’t regressed since it was fixed, as far as I remember. I don’t have the ability to close it though.

**Comment by kputnam** [comment]
Yes, this still occurs. It seemed to be fixed for quiet a while and has recently regressed. I will offer to look into it.

**Comment by kputnam** [comment]
Actually this issue could be closed. There is a separate issue regarding recent contacts: #5282
