### ISSUE TITLE
Deleted contact but still showing

### ISSUE THREAD

**Issue by claumrsk99** [signalapp/Signal-iOS#4892]
Deleted a contact from all places on my phone but i still see his contact info on my contacts list for signal. Does signal has a clear cache feature or delete all data from application?

**Comment by rb81** [comment]
I've faced this same issue. Only way to remove a deleted contact is to block the number (through Signal) then unblock. The contact no longer appears. Manually refreshing doesn't seem to work, nor does restarting the app.

**Comment by M00nD3v** [comment]
@rb81 Unfortunately this doesn't delete the contact but just hides it. When you search the contact name or any number, then you will see, that the contact is showing up and therefore not deleted.

**Comment by rb81** [comment]
> > I've faced this same issue. Only way to remove a deleted contact is to block the number (through Signal) then unblock. The contact no longer appears. Manually refreshing doesn't seem to work, nor does restarting the app.
> > ~@rb81
> 
> Unfortunately this doesn't delete the contact but just hides it. When you search the contact name or any number, then you will see, that the contact is showing up and therefore not deleted.

Either way, I guess we're both confirming the issue still exists ;)

**Comment by Flexmaen** [comment]
Here you also find a description of this problem:
https://www.reddit.com/r/signal/comments/l0he51/deleted_iphone_contact_still_shows_in_signal_as_a/

Should be fixed ASAP since this also is kind of a privacy issue.

**Comment by Flexmaen** [comment]
I think this is still an issue. The first post does not specify if this affects IOS or Android, but on Semptember this still was going on in IOS. Currently I tried to delete a contact in Android and it tells me "This contact contains information of multiple accounts. Data from write protected accounts can't be deleted, they'll be made invisible".

Since I didn't use this contact anywhere else, it seems like Signal is blocking a complete delete of this.

Also there is the same Problem with the desktop app: https://github.com/signalapp/Signal-Desktop/issues/4800

**Comment by El-Marti** [comment]
Yes, this is still an issue. I continue to see all my deleted contacts at the bottom of the list..... And this is not clean....

**Comment by VJ8919** [comment]
Can confirm the issue still stands. I have deleted a Signal conversation AND a relevant contact from all places in my phone but Signal does not register this. I have tried manual refresh in Signal but it does not work. The contact is still present in Signal. Very annoying indeed and a potential privacy issue.

**Comment by Flexmaen** [comment]
This is still going on and it's a privacy issue.

**Comment by El-Marti** [comment]
Yes, this is still relevant and as Flexmaen said, it's a privacy issue but also a basic expected behavior when we delete a contact from iOS.

**Comment by namzzz** [comment]
Still relevant. iOS 15.5.

I've spotted a way to delete 2 numbers of total 5 which reappeared at the bottom of the list after deleting them.

I've saved so called "undeleted" number with a random name to my Contact List again and deleted that contact again. But it didn't work with 3 others.

**Comment by M00nD3v** [comment]
This issue is still relevant.

**Comment by M00nD3v** [comment]
Why is this issue closed? It isn't fixed yet.
