### ISSUE TITLE
Notifications aren’t coming through. Neither are the calls. 

### ISSUE THREAD

**Issue by Ik3021** [signalapp/Signal-iOS#5072]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notifications aren’t coming through. Only when I am in the app, I receive messages and calls. If someone tries to call me, I only see a missed call. When I call back, my calls don’t get connected. This is impacting my day to day communication a lot. 

### Steps to reproduce
- using hyphens as bullets
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michaeljtknox** [comment]
Same issue on iPhone SE 2020, I think it started happening after iOS 14.7 update. 14.7.1 doesn't help. No notifications whatsoever until I open the Signal app.

**Comment by chipang** [comment]
same issue on Iphone 12 pro, with 14.7.1

**Comment by chipang** [comment]
https://debuglogs.org/fcb732a48652fb8a4706ff1c8e2f0fd1fff841a77eddc4b474d6f65e978f4ade.zip

mylog on failing to get notifications until actively open the app

**Comment by sebastiaanluca** [comment]
Have the same since a few days. Started happening after the latest Signal update, I assume.

No notifications anymore at all or sometimes a delayed notification for just one message while there are 5 new messages. I think I do receive the messages when the app isn't open, because the badge shows the unread count. Though it all depends, there are different situations.

**Comment by chipang** [comment]
> Have the same since a few days. Started happening after the latest Signal update, I assume.
> 
> No notifications anymore at all or sometimes a delayed notification for just one message while there are 5 new messages. I think I do receive the messages when the app isn't open, because the badge shows the unread count. Though it all depends, there are different situations.

Same situation, the situation exists after the latest (or 2 previous update) update.

For me, no notification at all for most time. So annoying.

**Comment by dagobertdebug** [comment]
Same situation here on a iPhone SE 2020 with iOS 14.7.1 

Needs a quick fix!!

**Comment by siuque123** [comment]
Not receiving notifications for 2 weeks! What is going on?

**Comment by wishin4thebeach** [comment]
iPhone 11 Pro having the same issue. Very frustrating

**Comment by IronJunkie** [comment]
Same issue I think 
#5083

**Comment by lbnelson** [comment]
Same issue on an iPhone 11 pro running 14.6, so I don't think it's related to the 14.7 or 14.7.1 iOS update.

**Comment by dagobertdebug** [comment]
Situation got better on my end during the last days. Notifications show up, mostly when connected to Wifi. 

How about everybody else?

@Signal Devs, has anything been changed related to this issue?

**Comment by kaimast** [comment]
I'm still experiencing this issue unfortunately. Is there something we can do to get this fixed quicker.

On the sending side I noticed that messages are not marked as send (two checkmarks) until the receiving party opens the app.

**Comment by siuque123** [comment]
Still the same, no notifications. Missing messages everyday. Considering to quit Singal!

**Comment by dagobertdebug** [comment]
After update to Signal version 5.18.3.0 no notifications!! What is going on??

**Comment by benlevy0** [comment]
I have the same issue. This breaks the app altogether and a high percentage of people I know who use Signal are experiencing this issue. To be frank, I'm astonished and disappointed. Signal is no longer an app with a small user-base that can break production for a full month.

https://debuglogs.org/f02cd006dad314f23c4884b9b999782dbab903ea5ee5bb156899bc6e30c77df5.zip

**Comment by kaimast** [comment]
It seems to have resolved itself for us today...

However, the app was not updated in a few days. Not sure if there was a server-side update, something changed on Apple's side or what else could have fixed it.

**Comment by parcelcat** [comment]
Still not resolved for me. iOS clients are not displaying notifications for new messages until the Signal app is manually opened.

**Comment by parcelcat** [comment]
Possibly related to #5066.

**Comment by kaimast** [comment]
I wonder if https://github.com/signalapp/Signal-Desktop/issues/5052 might be related? There something fishy going on with notifications on Signal these days.

**Comment by T4cC0re** [comment]
To add a data point here. I have the same behavior, but only for a subset of contacts.

In most groups and contacts I get notifications just fine, but there are 2 contacts I do not get any notification for. They are not blocked, nor have custom notification settings.

iPhone 12 Pro. Happened on iOS 14.7 as well as iOS 15 release and beta versions of iOS15.

This is really annoying. Especially because it happens with the contacts I communicate with most.

**Comment by AntonioALEA1996** [comment]
It also happens for me. I’m running iOS 15 RC, Latest App store version of Signal.

**Comment by onewil** [comment]
Experiencing same. Since iOS 15b7 or so. Two updates to signal since but neither have affected. It seems to be device specific as my iPad still gets notifications. Re-registering does not work. Server side issue? As others have noted no way to back up so not going to uninstall/reinstall randomly but this is quite serious as messaging without notifications is very hard to use.

**Comment by abhi6983** [comment]
Having the same issue after updating to iOS 15 on my iPhone XS. On the latest Signal version 5.20.2

https://debuglogs.org/77327b6af1f5cc32f8fb50837d480ae6931162348f3cbc73848c32f790feb73b.zip

**Comment by ghabiger** [comment]
I have the same issue, started with 14.7.1. I think.
Upgrading to iOS 15 did not fix this.

Re-Registering Push Notifications does not fix this.

This is beyond just 'annoying', it precludes Signal from being used as a messenger or messaging App.
If I can't get push notifications when people are trying to reach me, how am I supposed to use Signal for conversations?

Details:
iPhone Xs Max with iOS 15.0
Most recent/current version of Signal for iOS (5.20.2)
All permissions enabled for Signal in iOS Settings
Re-registered for push notifications etc.
Not in Focus/DnD Mode on the iPhone, other app notifications work just fine.

I simply receive no notifications from Signal whatsoever, and have to manually open the App and check whether new messages have arrived since I last opened it.


Please fix this, it's a bug that makes Signal basically unusable as a daily messaging solution, which sucks, because I've managed to persuade many friends to switch over from other apps recently.

**Comment by kakaofan** [comment]
same issue: no notification unless Signal is running in foreground. If i press home button to go to desktop. The notification still works within a minute.
Same thing happens if i swipe the app away(Force quit), no notifications any more

Device info:
Device: iPhone 6s Plus
iOS version: 14.8
Signal version: 5.20.x

**Comment by abhi6983** [comment]
I was able to resolve this issue by deleting and reinstalling the app. Now I’m receiving the messages and notifications without any issues.

Lost all my chats as I didn’t find any option to backup on my iPhone.

**Comment by JamesBaxter** [comment]
Just as another data point I am also having this issue.
iOS 15.0
iPhone 12
Signal 5.20.3.1
Messages are being delivered to my desktop but it seems like 100% aren’t coming to the phone unless the app is open.
Started experiencing it when I updated to iOS 15 but it’s possible the is updating caused my signal client to update?

**Comment by arunmv91** [comment]
Same issue here on ios 15. Please fix

**Comment by bcarrell** [comment]
Just adding another data point here that I have the same issue. No messages/notifications unless I open the app since updating to iOS 15.

iPhone XS Max
Signal ver 5.20.3.1

**Comment by lars-dev** [comment]
Same issue here
No notifications on my iPhone.
Only once i open the signal app i see the missed messages.

ios 15 iphone 12

firends told me about this bug and i thought. Surely they’re doing someting wrong on their phone bit it really seems to be a signal big.

**Comment by lattwood** [comment]
This was happening at one point on my iPhone 11 Pro. I migrated my signal data to a 13 Pro today and the notifications issue has appeared.

**Comment by pfr010** [comment]
Same issue here. No notifications for certain chats.

iphone 13 pro max, iOS 15.0.1

I tried:

> toggling notifications on/off in iOS settings 
> re-register push notifications
> delete chat
> delete and reinstall app

**Comment by arunmv91** [comment]
Yes. it's only happening in certain chats. the contact is in favorites and it's using the system contact image as display picture. 
This might help u guys in finding bugs.

**Comment by JamesBaxter** [comment]
I'm getting notifications on version 5.21.4.6 on iOS 15 now.

I'm glad to have them back and thankful for any work done to resolve but it was disconcerting to have Signal stop working in this way and as far as I can see never getting a response on the issue.

**Comment by song4Him** [comment]
I just started using Signal, and have no sound notifications. Have gone through all the settings I can think of to make it work, including resetting push notifications multiple times.

All message notifications work as they should (banner popup and message sound) when I have the app open and in the foreground. If I close the app (double-tap and swipe up to close foreground app) and have my screen turned off, the message notification will come in and the notification light will flash--but there is no notification sound. Haven't tested what would happen with a phone call yet.

iPhone 8
iOS 14.7.1
Signal 5.23.1.1

Debug log: https://debuglogs.org/59d28309554537e30e27b65eb7fb307587f44325b5e09d241c2322dfee61b451.zip

**Comment by michaeljtknox** [comment]
Little bit more info: The sender does not see the messages delivered until I open signal on my phone.
Is the app no running in the background like it should?

**Comment by michaeljtknox** [comment]
Still happening on 5.26.10.0. 
iOS 15.2.1
No news from anyone at Signal

**Comment by grankko** [comment]
Same issue for me, 15.2.1 / 5.26.10.0.

**Comment by bellbird22** [comment]
Still an issue for me--never have yet gotten sound with my notifications when my phone screen is turned off.

iPhone 8
iOS 15.2
Signal 5.26.9.2

(will be updating iOS and Signal soon, but as I see from others above, that doesn't make a difference)

**Comment by Cerberus0** [comment]
Hello everyone,

Signal iOS 5.29 beta now includes [a potential fix](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-5-29-release/41931):

>* Improvements to notification reliability. We know some of you are still experiencing issues with notification reliability and we’d love to hear if the 5.29 beta helps improve things for you or not, so please leave feedback if you notice a difference or even if you don’t.

If you want to help test it before release, [follow these instructions](https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta) to join the beta. You can leave feedback for this here or on the community forum, which you can easily join with your existing GitHub account.

**Comment by Lemmju** [comment]
I had exactly the same problem and tried the 5.29 beta. It fixed something, but not enough. 

With the public version, I had exactly the same situation than most here: no notifications were coming through until the app was opened. With the new version, I can receive notifications in some situations normally. Namely, some time after the app has been open. Then the notifications come to the lock screen / home screen (which they did not do before).

However, after the Signal app has been closed, it takes about 10 seconds and then the notifications stop coming. The problem does not seem to be related to the notifications, but to the app running on background. When the notifications stop, the sender sees that the message has not been delivered (only one check-circle), when the notifications work, the sender sees two non-filled circles.

Furthermore, at least with me, it seems that the notification starts a new 10 second interval, in which the notifications continue to come. So if I send messages with <10s intervals, the notifications keep coming. When the first >10s interval is hit, the notifications stop and the messages no longer go through.

Background app refresh is enabled, and I have tried to disable&enable it many times, no help from there. Data saver is not enabled, and the operation is the same with mobile & WiFi. Low Power Mode is not enabled.

**Comment by bellbird22** [comment]
Notifications are still an issue for me, but different from what @Lemmju describes. I submitted a report via TestFlight...hope that got through to the right place!

**Comment by T4cC0re** [comment]
I have just linked a bunch of issues dating back to 2019. Can someone from the Signal dev team please take a look at this? This is very much still a huge problem!

**Comment by johncronan** [comment]
I previously had a little bit of luck with @'ing @Imperiopolis-Signal 

https://github.com/signalapp/Signal-iOS/issues/4652#issuecomment-902451759

IMO we need more information about how the iOS Background Processing is affecting Signal. iOS has a more complex and opinionated system than Android, from what I understand. This is a nexus of power. It would be nice to get some reassurance that Apple is not abusing it.

**Comment by T4cC0re** [comment]
> It would be nice to get some reassurance that Apple is not abusing it.

Given that literally all other messaging apps I have on my phone (FB messenger, WhatsApp, IRCCloud, etc) work just fine, I strongly believe this is something to do with how Signal does Notifications.

**Comment by michaeljtknox** [comment]
It was working for me 2 weeks ago and then it all went downhill. Back to opening the app to see if I have new messages.
Please let me know if anyone needs info (versions, logs etc.)

**Comment by Naxterra** [comment]
I have the same issue. No notifications and sound are coming from the app when phone is locked. 

iPhone 13 Pro Max - iOS 15.5
Signal 5.41.0.12

Reinstalling app didn't solve the issue. I also tried beta versions, but they had the same problem. This issue is going on for months.

Focus mode is not active, notifications are active.

Here is my log.

[2dd9f5cc69a78d83f10087eed2c9711fb30e12b8536e97ee76a2c2f8a564ea49.zip](https://github.com/signalapp/Signal-iOS/files/8936277/2dd9f5cc69a78d83f10087eed2c9711fb30e12b8536e97ee76a2c2f8a564ea49.zip)

**Comment by Naxterra** [comment]
I still can't get any notifications with sound.
iPhone 13 Pro Max - iOS 16 Public Beta
Signal 5.44.0.10

I followed https://support.signal.org/hc/de/articles/360007318711-Problembehebung-bei-Benachrichtigungen#ios_notifications_troubleshooting but still same issue. Notifications have sound only when app is open. When phone screen is off, no notification sounds are coming.

**Comment by Lemmju** [comment]
I switched to a new device and the issue has been fixed (for now). I suspect that this issue is somehow related to the iOS upgrades that are made while the app is installed. The rights have not transferred correctly in all occasions, and removing / re-enabling them did not help.

With the old phone, I started to get the same problem with WhatsApp also. There the notifications could be delayed for up to an hour, with the same kind of symptoms than with Signal.

**Comment by T4cC0re** [comment]
Switching to a new device did not fix it for me. (From iPhone 12 Pro iOS 16.0 to iPhone 14 Pro Max iOS 16.0.1)

**Comment by michaeljtknox** [comment]
Still having intermittent issues as well as my contacts who message after a few days: sorry I never got a notification until I opened the app. This is far from fixed…
________________________________

**Comment by bellbird22** [comment]
Still getting no notifications with sound...updating iOS and app software multiple times has done nothing to help.

**Comment by bellbird22** [comment]
This is still an issue for me—I still am receiving no notifications with sound.

**Comment by michaeljtknox** [comment]
Still an issue for me and a lot of my contacts who are on iOS or Android.

**Comment by bettabacon** [comment]
I primarily notice this with senders that are on AndroidOS sending to my iOS. I have to open and app, and then some seconds later, an avalanche of messages come in. I can't say for sure that it happens as much from iOS senders. As many have said, I also noticed this an issue when upgrading to/from iOS v14.7.x Oddly enough, upgrading to iOS v15 did not help. Re-registering push notifications does not help at all. I am using the Lockdown VPN app. It uses the loopback address and has a local database, blacklisting advertising IPs, but I can't see how that might affect or delay Signal's protocol and notifications.

**Comment by putnam** [comment]
I discovered something tonight that may be relevant/interesting to Signal iOS devs.

If you have an Apple Watch *and* notification mirroring enabled for Signal, you can get into a situation where notifications are swallowed into a black hole. Since iOS/watchOS prioritize the watch, the notification is sent to the watch and the screen doesn't light up or play any sounds on the phone. Not totally unexpected if you actually get the notification on the watch. However as recently as tonight I was able to repeatedly reproduce a situation where the notification never appeared on the watch, and never lit the screen/made a sound on the phone. Only once I disabled mirroring notifications to the watch did it begin working on the phone again.

Then, I rebooted the watch. Suddenly mirrored notifications worked again. Signal was up to date both before and after this occurred. iOS and watchOS were also on latest version.

Just wanted to mention this potential path -- not sure if this is an Apple problem or a Signal problem. Other apps with mirroring enabled worked fine; it seemed to only be Signal. Toggling off/on didn't make a difference.

**Comment by T4cC0re** [comment]
> Just wanted to mention this potential path -- not sure if this is an Apple problem or a Signal problem. Other apps with mirroring enabled worked fine; it seemed to only be Signal. The only thing that worked for me to get notifications behaving properly again was a full reboot of the watch.

This is certainly interesting! Nice find!

I don’t think it’s the only case notifications get swallowed, since I still have some contacts where the issue persists. But maybe this provides a new angle to debug the issue.

I would certainly wish signal's notifications would be reliable :)

**Comment by bellbird22** [comment]
A great observation! But yes, that’s certainly not all. I don’t have an Apple Watch, so that won’t be my problem. I always get notifications on my lockscreen and in my notifications center, but ONLY get sound with said notifications if my phone is unlocked.

**Comment by T4cC0re** [comment]
This is still relevant

**Comment by FopseN** [comment]
Having the same problem on a new iPhone 15 Pro Max.

**Comment by Miguel-Signal** [comment]
Hi @FopseN @T4cC0re

Could you please email your debug logs to support@signal.org? To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.
