### ISSUE TITLE
Cannot turn off screen while on a call without headphones

### ISSUE THREAD

**Issue by XHotSniperX** [signalapp/Signal-iOS#5313]
### Bug description
When trying to turn off the screen by pressing the lock button to save power while on a call, it simply aborts the call. The lock button should simply lock the phone and not abort the call.

### Steps to reproduce
- Open Signal
- Call someone without headphones. Simply use loudspeakers
- Press the lock button to darken the screen

**Actual result:** Phone call aborted

**Expected result:** Phone call continues and screen turns off to save power

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 15.4.1

**Signal version:** 5.34.1.0

**Comment by Flamity** [comment]
I can vouch this has been an issue for my iPhone XS for close to a year. If I call someone, I can press the power button and it will continue the call in sleep mode. But if they call me and I press the power button, the call ends. It's really annoying and has messed with our calls non stop.

**Comment by XHotSniperX** [comment]
Looks like this issue has been fixed with version 5.35.2.0. Thanks for solving it :)

**Comment by readstead** [comment]
It's not fixed. It's still happening and makes using Signal a huge chore. Please reopen this and/or the duplicate #4167.
