### ISSUE TITLE
App crashes on open

### ISSUE THREAD

**Issue by alexanderepolite** [signalapp/Signal-iOS#5333]
https://user-images.githubusercontent.com/88310235/165992234-6ed61323-c4d1-4228-a2c6-9a9120511c19.MOV

iPhone 7+
iOS 15.3.1
Signal 5.36.0

**Comment by smt311** [comment]
same as my friend, she has updated to signal 5.36 and using ios 15.4.1.
Please fix it

**Comment by karo431** [comment]
Reproducible on iPhone 8, iOS 14.8, v. 5.36.0

**Comment by tonycch** [comment]
Same here on iPhone 11 Pro running iOS 14.7, not even able find the crash report

**Comment by Katharina134** [comment]
Same here on iPhone SE running iOS 15.4.1. Have you been able to solve the problem?

**Comment by Katharina134** [comment]
I wonder should I wait for the next update or deinstall/reinstall the app (but then all my content is gone.....). What will you guys do..?

**Comment by alexanderepolite** [comment]
> Same here on iPhone SE running iOS 15.4.1. Have you been able to solve the problem?

@Katharina134 no, i will respond if i find something, most likely there will be an update to fix it

**Comment by Katharina134** [comment]
> > Same here on iPhone SE running iOS 15.4.1. Have you been able to solve the problem?
> 
> @Katharina134 no, i will respond if i find something, most likely there will be an update to fix it

Thank you :-) I really hope so...relieved others have the same problem!

**Comment by UriAnteo** [comment]
Same problem here on an iPhone 12 Pro, newest OS version - with the new update, signal won’t even open.

**Comment by sanneboshuizen** [comment]
Same here. IOS 15.4.1  Iphone SE Please Fix!!

**Comment by tonycch** [comment]
> I wonder should I wait for the next update or deinstall/reinstall the app (but then all my content is gone.....). What will you guys do..?
> 
> 

On iOS you can try [offloading the app](https://www.payetteforward.com/offloading-apps-on-iphone-what-it-means-why-you-should/amp/) to retain data over reinstall, however I tried reinstalling but it does not help in this case. Need to wait for a proper fix.

**Comment by awltr** [comment]
Same here. iOS 15.4.1 Signal 5.36.0 iPhone 11.

**Comment by toonconvents** [comment]
Same here. Latest IOS, Signal 5.36.0.

**Comment by aleifer** [comment]
Same here.

**Comment by smt311** [comment]
What can we do? Can we reinstall the app to fix this problem?

**Comment by tanguero8280** [comment]
I hav the same problem with Iphone 7 and Signal 5.36.0. Cicking Signal Icon, nothing happens.
Any solution without loosing correspondence??

**Comment by alexanderepolite** [comment]
> I hav the same problem with Iphone 7 and Signal 5.36.0. Cicking Signal Icon, nothing happens.
> 
> Any solution without loosing correspondence??

i don't think so, signal will probably push an update soon that'll fix it

**Comment by Katharina134** [comment]
> What can we do? Can we reinstall the app to fix this problem?

i personally hesitate, because all my correspondence will be lost. signal in iOS doesnt provide backup-opportunity...

**Comment by awltr** [comment]
> > What can we do? Can we reinstall the app to fix this problem?
> 
> 
> 
> i personally hesitate, because all my correspondence will be lost. signal in iOS doesnt provide backup-opportunity...

From a theoretically point of view I think that could help. But I read on reddit that it didn't. So probably don't risk your data and wait until beginning of next week. Hope they will fix it.

**Comment by awltr** [comment]
Could anyone provide a debug log? My device is showing nothing in Analytics Data.

**Comment by tonycch** [comment]
Fixed in 5.36.1 👍

**Comment by 0sprei** [comment]
Thanks for the fix!  Signal 5.36.1 is now working for my phone using iOS 15.4.1.

**Comment by Katharina134** [comment]
Thank you, working again!!

**Comment by EvanHahn-Signal** [comment]
Indeed—this should be fixed in 5.36.1. Sorry about this!

**Comment by beingke** [comment]
Still happening on 5.37.1.0. Signal crashes right after entering an existing conversation.

**Comment by alexanderepolite** [comment]
> Still happening on 5.37.1.0. Signal crashes right after entering an existing conversation.

@beingke  not happening for me, also 5.37.1.1 is out.

you should create a new issue if this persists, rather than replying to an old (and closed) issue.

**Comment by beingke** [comment]
Thanks for the heads-up, I will create a new issue then.

**Comment by alexanderepolite** [comment]
Wait for an update, probably.
