### ISSUE TITLE
Signal UI bug iOS 16 iPhone 14 Pro (dynamic island)

### ISSUE THREAD

**Issue by castanley** [signalapp/Signal-iOS#5437]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
iOS 16 on iPhone 14 pro with dynamic island has a text message UI issue where the scrolling of the message goes above the top notification bar. This is likely due to the new “dynamic Islam” UI change from Apple and likely only affects newer iPhones with said island. 

### Steps to reproduce
- buy an iPhone 14 Pro with dynamic island
- open signal
- Go to a message that scrolls 
- Watch it go above the top UI

**Actual result:** The messages go above the UI

**Expected result:** The messages don’t go above the UI

### Screenshots
![51CB0CB4-54AD-4228-8C8A-767CCAE52BC5](https://user-images.githubusercontent.com/5520895/190881254-6db1a558-2849-4915-8c9a-5913aa79584b.jpeg)

### Device info

**Device:** iPhone 14 Pro
**iOS version:** 16.0.1
**Signal version:** 5.51.0.14

**Comment by Kiyozz** [comment]
I can confirm.

**Comment by FbnGnstn** [comment]
For me as well 👍

**Comment by jonsherrard** [comment]
Seeing this on 16.0 and 16.0 

iPhone 14 Pro

![image](https://user-images.githubusercontent.com/631670/190877420-3caefc33-b782-460e-94b4-504d0eb22371.jpeg)

**Comment by WorldIRC** [comment]
Affects me as well!

**Comment by nows54** [comment]
I'm facing this issue too.
It seems to be related to dark mode. Switching to light theme, killing the app and next restart should be ok (as temporary fix)

**Comment by Kiyozz** [comment]
> I'm facing this issue too.
> 
> It seems to be related to dark mode. Switching to light theme, killing the app and next restart should be ok (as temporary fix)

Not for me. Dark or Light, does not matter

**Comment by Jeanmarchp** [comment]
Having the same issue

**Comment by wormeyman** [comment]
They are aware of the issue and just got their physical iPhone 14's. https://whispersystems.discoursehosting.net/t/chat-displayed-above-header-status-bar-on-iphone-14-pro/47285/6

> Hey folks! We just got our own iPhone 14 pro devices (this doesn’t seem to happen on simulators), and are looking into this ASAP. Thanks for sharing feedback!

**Comment by WorldIRC** [comment]
This is now resolved

**Comment by Lundeful** [comment]
Great work guys! 👍

**Comment by Lundeful** [comment]
> This is now resolved 

In which pull request/commit? 😊

**Comment by phinnaeus** [comment]
It's in the App Store. Just update.

**Comment by Lundeful** [comment]
Was able to get the update. Seems like it's working. 

Great work guys! Quick turnaround on this issue 😀❤️

**Comment by PattaFeuFeu** [comment]
![grafik](https://user-images.githubusercontent.com/9012887/191497122-fa74ca18-34d7-4fff-bd7f-db74de7fa1d3.png)

Fixed in 5.51.2.0 👌

**Comment by Salamafet** [comment]
The bug is back in version 5.58.0.12.

![image](https://user-images.githubusercontent.com/783351/198252209-6c3b0110-dce0-447d-8f3c-ae223dec2053.png)

**Comment by WorldIRC** [comment]
The bug has returned in 5.58.0.12

**Comment by Lundeful** [comment]
> The bug has returned in 5.58.0.12

It is not back for me it seems.

I checked I have Signal version 5.58.0.12 and iOS version 16.1 (20B82) on my iPhone 14 pro (not max).

**Comment by Salamafet** [comment]
Back for me too, but not every time. Unable to find what is triggering this bug.

**Comment by WorldIRC** [comment]
My phone just switched to light mode and went away. Perhaps it's a dark mode glitch this time?

**Comment by WorldIRC** [comment]
> Thanks for the feedback everyone! As stated, this issue should be fixed in the latest AppStore build (5.51.2), please update if you haven't yet.

FYI the bug has returned.  Quoting so you can reopen this.

**Comment by WorldIRC** [comment]
5.59.0.18 appears to re resolve this. Live in the App Store now.
