### ISSUE TITLE
Clicking 'Send' clears the input field but no message is being sent

### ISSUE THREAD

**Issue by somerandom2** [signalapp/Signal-iOS#5598]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Cannot send message, cannot enter stories section, cannot enter "Change Phone Number" section after 6.24.0 update.

### Steps to reproduce
- Open Signal
- Send message to previously chatted person, or go to stories, or go to "Change Phone Number" section.

**Actual result:** Cannot send message. It is hanging and don't send message. I have to send via desktop signal. 

**Possible error**
When I analyze debug log I saw these lines.
2023/05/20 06:57:11:555  ❤️ [MessageSender.m:280 -[OWSSendMessageOperation didFailWithError:]]: Failed with error: <SignalServiceKit.MessageSenderNoSuchSignalRecipientError: 0x106823aa0> (isRetryable: 0)
2023/05/20 06:57:11:561  💛 [NotificationService.swift:253 fetchAndProcessMessages(logger:)]: Pending outgoing message complete {{[ REDACTED_UUID:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxE74 ]}}
2023/05/20 06:57:11:561  ❤️ [OWSOutgoingReceiptManager.m:273 -[OWSOutgoingReceiptManager sendReceiptsForReceiptType:]_block_invoke]: Failed to send Viewed receipts to sender with error: <SignalServiceKit.MessageSenderNoSuchSignalRecipientError: 0x106823aa0>

### Device info

**Device**: iPhone XS

**iOS version**: 16.5

**Signal version:** 6.24

### Link to debug log
https://debuglogs.org/ios/6.24.0/cbec59918b9ba96f8357fa7c95a86ccd47ed63a61f79affab6a52b0d622810d5.zip

**Comment by somerandom2** [comment]
Please consider this. I still cannot use Signal IOS. I have to open desktop Signal everytime I want to send message.

**Comment by somerandom2** [comment]
Sorry for accidental close.

**Comment by martin-fink** [comment]
I'm experiencing the same issue (same error in the log as well).
I am however able to use Signal on my iPad.

Just a note to @somerandom2: For better discoverability, it might be good to change the issue title to something that describes the problem, such as "Clicking 'Send' clears the input field but no message is being sent" or something similar.

**Comment by somerandom2** [comment]
I changed title. Thank you.

**Comment by somerandom2** [comment]
After 6.27 update it is fixed. Thank you.

**Comment by martin-fink** [comment]
For me, the issue is still there with the latest update. The errors in the debug log have changed, however.
I now see issues like the following:

```
2023/06/09 15:04:08:909  ❤️ [PushRegistrationManager.swift:130 didReceiveVanillaPushToken(_:)]: promise completion in didReceiveVanillaPushToken(_:) unexpectedly nil
...
2023/06/09 16:58:50:029  ❤️ [ProfileFetcherJob.swift:641 addBackgroundTask()]: background task time ran out before profile fetch completed.
...
2023/06/09 16:58:54:944  ❤️ [OWSBackgroundTask.m:231 -[OWSBackgroundTaskManager startBackgroundTask]]: background task could not be started.
2023/06/09 16:58:54:945  ❤️ [OWSBackgroundTask.m:409 -[OWSBackgroundTask startBackgroundTask]]: applicationWillResignActive background task could not be started.
2023/06/09 16:58:54:945  💛 [OWSBackgroundTask.m:195 -[OWSBackgroundTaskManager ensureBackgroundTaskState]]: Starting background task.
2023/06/09 16:58:54:945  ❤️ [OWSBackgroundTask.m:231 -[OWSBackgroundTaskManager startBackgroundTask]]: background task could not be started.
2023/06/09 16:58:54:945  ❤️ [OWSBackgroundTask.m:409 -[OWSBackgroundTask startBackgroundTask]]: applicationWillResignActive background task could not be started.
...
2023/06/09 17:03:48:996  ❤️ [GroupV2UpdatesImpl.swift:429 didFail(error:)]: failed with error: timeout
```

Should I open a new issue?
