### ISSUE TITLE
Invalid response from service when sending message from linked iPad device

### ISSUE THREAD

**Issue by J-a-n-u-s** [signalapp/Signal-iOS#5653]
- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Starting August 24 2023, when trying to send messages using a linked iPad, I began getting "Invalid response from service" errors. Retrying doesn't reproduces error. When sending message from original device, messages send properly, and show up on the iPad.

### Steps to reproduce
- Link iPad
- Try to send message

**Actual result:**  "Invalid response from service" error

**Expected result:** Message should be sent properly

### Device info
**Device**: iPad mini gen 6

**iOS version**: 16.6

**Signal version:** 6.37.0.8

### Link to debug log
https://debuglogs.org/ios/6.37.0/2d9aa4da7e1bfc0fce7e5b0cb5855cb8b4fbe2d9b2db036662f3c9ee24106395.zip

**Comment by harry-signal** [comment]
Hi, thank you for the report! This should be fixed in version 6.38, which is now available on the AppStore if you manually update.

**Comment by J-a-n-u-s** [comment]
@harry-signal +1 for responsiveness! Downloaded update this evening and sadly problem persists. Here is new debug log:

https://debuglogs.org/ios/6.38.0/bca50f66eb7ad891aad0bba908b7397719b7e316d8b97d60f388db6216bbe409.zip

If I can help in any way, don't hesitate to ask.

**Comment by harry-signal** [comment]
Huh! This is different than the issue we saw before, and very useful logs. Thank you! We will be taking a look at this after the weekend.
