### ISSUE TITLE
Bluetooth headset issues

### ISSUE THREAD

**Issue by axxe** [signalapp/Signal-iOS#737]
iPhone 5s, iOS 8.1.3, Signal 2.0, Bluetooth headset (Plantronics Voyager 510). iPhone says headset is connected, and when a calls comes in on Signal, I get the chirp over the headset that normally precedes a live audio connection, but audio remains on the iPhone speaker. Headset works fine with the phone otherwise, and headset used to work with the earlier version of Signal under iOS 7.1.2.

**Comment by FredericJacobs** [comment]
What happens if you tap on the speaker icon, does it switch to the other speaker?

**Comment by FredericJacobs** [comment]
(I don't own any Bluetooth devices headset so it's hard for me to try)

I believe I have a fix. Can you send me an email at fred@whispersystems.org? I will send you a build to try.

**Comment by FredericJacobs** [comment]
Hey,
I think I will let the issue resolve itself. It was a known bug in iOS8. According to iOS 8.3 release notes this should be fixed! Feel free to reopen if this happens again.

**Comment by FredericJacobs** [comment]
@axxe : did you encounter this issue again lately?

**Comment by axxe** [comment]
The problem remains.

iOS8.3 with Bluetooth headset "Connected" in Bluetooth settings (and verified to work with a standard voice call).  Using Signal I can only get audio through the iPhone's headphone jack or internal speaker.  No amount of fiddling with the Headset (restarting, disconnecting, reconnecting) has any effect in Signal.

On Apr 14, 2015, at 16:00, Frederic Jacobs <notifications@github.com> wrote:

> @axxe : did you encounter this issue again lately?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Axel Essbaum
axel@essbaum.com

**Comment by Ewarren7** [comment]
Hey, I also can confirm this bug in iOS 8.3 and Signal 2.0.3 and various bluetooth devices. Bluetooth used to work great but when the last major UI change happened it broke. It works occasionally but it usually doesn't. I have yet to find the commonalities. 

Toggling the speaker button only switches between the internal speaker and the external speaker. 

Thanks

**Comment by brianwmsn** [comment]
Confirmation here that Bluetooth is not working with Signal 2.1.1 and iOS 8.4.

**Comment by JimLoose** [comment]
Yups, confirmed here as well (sorry about the duplicate issue)

**Comment by brianwmsn** [comment]
Tried again with 2.2 update. It did work with a headset however I can hear myself speaking in the headset (with a slight echo). The other party indicated they could hear me ok.

**Comment by ahoogerhuis** [comment]
When using Bluetooth hands free there is no ring tone in the hands free unit, but once the receiver picks up a call the call is heard in the hands free unit.
During the ringing phase the ringtone is in the handset even when all other audio is in the hands free unit.
Bug exists with both iPhone 6 and 6s.

**Comment by ksylvan** [comment]
I can verify that something like this is still happening on iOS 10.3.3 with Signal 2.12.2 on iPhone 7 Plus.

When I receive a call, it rings in the BlueTooth headset, but when you answer it, the only two audio choices are the iPhone and iPhone speaker (no BlueTooth). When I call someone, I heard some ringing in the headset, but when the call is picked up, again, no sound in the headset.

**Comment by timothy-symanczyk** [comment]
Just to chime in, this is (still) an issue with iPhone 6S+, iOS 10.3.2 (latest available for me), and Signal 2.13.4.0,

Bluetooth headset successfully connected and functioning with other apps. Call comes in, for a brief second I can see the "regular" phone screen with the six buttons where one has the option to change the audio - then it immediately switches to phone audio, and only shows the mute call-end and speaker-phone options. Outgoing calls also only show the same three buttons.

Thanks for looking into this, Signal is awesome.

**Comment by michaelkirk** [comment]
I believe this has been fixed for the next release. If you're interested in trying out the beta, once it's released, you could let us know if it's working with your setup.

To sign up contact support@whispersystems.org.

**Comment by timothy-symanczyk** [comment]
Tested and confirmed working now in current beta. Tried with both incoming and outgoing calls. Thanks so much!

(Signal 2.14.0.4, iPhone 6s+, iOS 10.3.2(14F89)

**Comment by ksylvan** [comment]
Confirmed working as well. Thank you!

iPhone 7Plus. iOS 10.3.3 (14G57)

**Comment by riyapenn** [comment]
Closing as this is now in [2.14.0 and is available to all](https://signal.org/install).

**Comment by timothy-symanczyk** [comment]
I hate to say this, but I'm hitting this same bug in the release version (2.14.0.4). I can't get bluetooth to work anymore, when it worked great in the beta.

**Comment by timothy-symanczyk** [comment]
Just to clarify my last comment - during the beta, I tried it both ways with one friend and it worked great. Later on the release version, phoned a different friend and did NOT have the option for bluetooth. Tried the release version again just now with my original friend (where it worked with the beta) and it bluetooth indeed worked with them. If there's anything I can test or try or clarify please let me know.

**Comment by michaelkirk** [comment]
@timothy-symanczyk next time this occurs, can you submit a debug log right after the call?

**Comment by timothy-symanczyk** [comment]
Absolutely, happy to.

Spent a few minutes calling back and forth with the friend I saw the bug with, including calls both directions and closing the app etc - could not reproduce (frustrating!). I'm as certain as I can be though that I saw this bug on the release version two nights ago - and will certainly submit the debug log the next time I see it.

If you want to close the bug for now until I can prove it, or someone else chimes in, it wouldn't offend me.

**Comment by michaelkirk** [comment]
>  I'm as certain as I can be though that I saw this bug on the release version two nights ago - and will certainly submit the debug log the next time I see it.

I believe you =)

But it sounds like it's an intermittent / random bug rather than related to your particular hardware or who you are calling. So that's helpful information already.

**Comment by mailinglists35** [comment]
I get *precisely* the same behaviour as described in first message.
Debug logs https://debuglogs.org/1ed12186efa48508c977bc1dbecd9d1abf7fbe560b5a420f47f68c683c82acba.zip1

**Comment by mailinglists35** [comment]
I can't edit message on github from phone, just want to add what is different from op (debug log should tell this anyway; mind the extra character at the end of the url added to prevent scavenging bots from crawling it)

iphone se

ios 10.2

latest testflight

**Comment by mailinglists35** [comment]
@michaelkirk did you get any chance to look at the provided debug log?

**Comment by mailinglists35** [comment]
@michaelkirk-signal

**Comment by 211217613** [comment]
Can confirm bluetooth issues in the more recent releases and other bluetooth issues over all.

**Comment by Trojgarb** [comment]
The same issue on Moto X Force with Nougat 7.0.

**Comment by MacUserMiss** [comment]
Hello!

Same issue over here. When I am recording voice messages on Signal the iPhone records the sound from the internal microphone and ignores the fact I am wearing my AirPods Pro. Annoying when you want to carry your phone in your purse and keep your hands warm in your winter jacket!

Same issue described here:
https://www.reddit.com/r/signal/comments/id6nfn/using_the_mic_airpods_with_signal_voice_messages/

Is there gonna be a fix soon?

iPhone XS
Signal 3.21.3.0

**Comment by robin13** [comment]
Duplicate of https://github.com/signalapp/Signal-Android/issues/12016 I think.
